### ISSUE TITLE
All integer named parameters mapped to bigint

### ISSUE THREAD

**Issue by kosinsky** [microsoft/go-mssqldb#16]
**Describe the bug**
Query like:
```go
res, err := db.Query(`SELECT COUNT(*) FROM test WHERE partition_id=@partitionId`,
	sql.Named("partitionId", int(1)))
```
executed as:
```SQL
exec sp_executesql N'SELECT * FROM test WHERE partition_id=@partitionId',N'@partitionId bigint',@partitionId=1
```
`partitionId` parameter defined as `N'@partitionId bigint'` even in code we are using `int` not `int64`

It's important, because plan will have implicit cast and as a result may be suboptimal plan especially when using partitions.

For example, if table was defined with partitions schema (notice that partition column is int):
```SQL
DROP TABLE IF EXISTS test;
			IF EXISTS(SELECT * FROM sys.partition_schemes WHERE name='ps')
			BEGIN
				DROP PARTITION SCHEME ps;
			END
			IF EXISTS(SELECT * FROM sys.partition_functions WHERE name='pf')
			BEGIN			
				DROP PARTITION FUNCTION pf;
			END
			CREATE PARTITION FUNCTION pf (int) AS RANGE LEFT FOR VALUES (0,1,2);
			CREATE PARTITION SCHEME ps AS PARTITION pf ALL TO('PRIMARY');
			CREATE TABLE test(partition_id int, id bigint) ON ps(partition_id);
			CREATE UNIQUE CLUSTERED INDEX pk on test(partition_id, id)
			INSERT INTO test values(1,1);
```
Plan with `,N'@partitionId bigint'` will look like (notice greater/less then comparison):
![image](https://user-images.githubusercontent.com/4909055/167693470-5a655fdd-d8a6-4999-9b32-12834e8e5e85.png)

Plan with `,N'@partitionId int'` will look like (equality comparison, expected):
![image](https://user-images.githubusercontent.com/4909055/167693412-05aad291-6ab3-44ab-94e3-b9531f2f0149.png)Note: problem with partitions is only one case of problems caused by implicit cast.

**To Reproduce**
Run SQL profile to see what is executed: 
```go
package main

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/jmoiron/sqlx"
	_ "github.com/microsoft/go-mssqldb"
)

const CONNECTION_STR = "sqlserver://sa:<yourpassword here>@127.0.0.1:1433?database=D1"

func main() {

			IF EXISTS(SELECT * FROM sys.partition_schemes WHERE name='ps')
			BEGIN
				DROP PARTITION SCHEME ps;
			END
			IF EXISTS(SELECT * FROM sys.partition_functions WHERE name='pf')
			BEGIN			
				DROP PARTITION FUNCTION pf;
			END
			CREATE PARTITION FUNCTION pf (int) AS RANGE LEFT FOR VALUES (0,1,2);
			CREATE PARTITION SCHEME ps AS PARTITION pf ALL TO('PRIMARY');
			CREATE TABLE test(partition_id int, id bigint) ON ps(partition_id);
			CREATE UNIQUE CLUSTERED INDEX pk on test(partition_id, id)
			INSERT INTO test values(1,1);
			`); err != nil {
		fmt.Println("Error", err)
		return
	}

	res, err := db.Query(`SELECT COUNT(*) FROM test WHERE partition_id=@partitionId`,
		sql.Named("partitionId", int(1)))

	if err != nil {
		fmt.Println("Error", err)
		return
	}

	res.Next()
	cnt := 0
	err = res.Scan(&cnt)
	if err != nil {
		fmt.Println("Error", err)
		return
	}

	fmt.Println(cnt)

}
```
In SQL profiler you could see what was executed. Run query in SSMS to see the plan

**Expected behavior**
It should be executed as
```SQL
exec sp_executesql N'SELECT * FROM test WHERE partition_id=@partitionId',N'@partitionId int',@partitionId=1
```
Parameter passed as `,N'@partitionId int'`

**Comment by shueybubbles** [comment]
This may be common across `database/sql/driver` implementations due to use of https://pkg.go.dev/database/sql/driver#DefaultParameterConverter

Should go-mssqldb implement Int and BigInt types like it does for VarChar etc  in https://github.com/microsoft/go-mssqldb/blob/2c7e9d5c12b847ce2a629d3d72bf66f52e204837/mssql_go19.go#L43 ?

With such a type, the app could specify the parameter using `mssql.Int(value)` or `mssql.BigInt(value)`, though that has a disadvantage of requiring apps to couple themselves to mssql types.

**Comment by shueybubbles** [comment]
@kosinsky `int` is a problematic type in Go, as it is 32bit on 32bit processors and 64bit otherwise.

Is it reasonable to expect an app to use `int32` when they need a 32bit int on SQL when the app is 64bit? Otherwise, we would have to see if the value of the `int` fits in the 32bit range and use a 4 byte value, else use an 8 byte value. Since we don't know the type of the parameter in the SQL query we don't know if converting a 64bit value to a 32bit value is what the app author really intended.

**Comment by kosinsky** [comment]
>@kosinsky int is a problematic type in Go, as it is 32bit on 32bit processors and 64bit otherwise.

You right. I meant `int32`, not platform specific `int`.
* `int64` - `bigint`
* `int32` - `int`
* `int16` - `smallint`
* `int8` - `tinyint`
