### ISSUE TITLE
Always Encrypted - get it working

### ISSUE THREAD

**Issue by lokmannicholas** [microsoft/go-mssqldb#56]
- What is the correct connection string for Always Encrypt?
- How to integrate with Key Vault?
- Any example to Insert or Update the data?

I have an issue with updating an encrypted field. 
For example:
My table `members` has an column `dob` which is encrypted

I can exec it in Azure studio, but cannot implement in code.
```
DECLARE @dob varchar(10) = '2022-06-01';
Update members SET dob  = @dob where id = '123';
```

I always get `The encryption scheme for the columns/variables is (encryption_type = 'PLAINTEXT') and the expression near line '2' expects it to be DETERMINISTIC, or PLAINTEXT.`

Thanks

**Comment by wcraigjones** [comment]
Did you have any success getting this to work @lokmannicholas ?

**Comment by shueybubbles** [comment]
Does this driver even claim support for AE? It looks like this PR never got in:
https://github.com/denisenkom/go-mssqldb/pull/637

**Comment by nicholas-atg** [comment]
> Did you have any success getting this to work @lokmannicholas ?

it doesn't work, i am finding someone to make it work together @@

**Comment by shueybubbles** [comment]
We are building a multi-phase plan for AE. Each phase corresponds to a complete set of functionality that can be released.
Phase 1 - 
a. Define the connection string (including enclave settings)
b. Define a key provider interface, including how to pass along authentication parameters
c. Implement the AKV key provider
d. Configurable CEK cache 
e. E2E testing of decrypting using AKV. This part will likely be done internally since it requires a real Azure sub.
Phase 2 -
a. Support for encryption of parameters in parameterized queries
b. Add a local certificate key provider
c. Enclaves
Phase 3 -
a. Performance tuning
