### ISSUE TITLE
implement SQL Server Utilities Statements - GO

### ISSUE THREAD

**Issue by comsma** [microsoft/go-mssqldb#72]
I would like to be able to use the GO statement within my sql statement so I can run batches.

**Comment by shueybubbles** [comment]
We have a `sqlcmd` script execution package at https://github.com/microsoft/go-sqlcmd/pkg/sqlcmd that might be appropriate. If you provide the sqlcmd instance with your own implementation of [Formatter](https://github.com/microsoft/go-sqlcmd/blob/9b59da694f9cbdf87acf70589e4c680589917f1a/pkg/sqlcmd/format.go#L23) you'll get access to the driver data.

**Comment by comsma** [comment]
would I replace the go-mssql import? This is how i'm currently using the package

```go
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/microsoft/go-mssqldb"
	"math"
	"os"
)

var db *sql.DB

func main() {

	files, _ := os.ReadDir(".")

	openDb("sqlserver://xxx")

	batches := len(files) / 500
	batches = int(math.Round(float64(batches)))
	fmt.Println(batches)

	for batch := 0; batch < batches; batch++ {
		sendScriptsAsQuery(files[(batch*500)+0 : (batch*500)+500])
	}

	sendScriptsAsQuery(files[2000:2500])
	defer db.Close()

}

func openDb(connectionUrl string) {
	var err error
	db, err = sql.Open("mssql", connectionUrl)
	if err != nil {
		fmt.Println("Cannot connect: ", err.Error())
		return
	}
	err = db.Ping()
	if err != nil {
		fmt.Println("Cannot connect: ", err.Error())
		return
	}
}

func sendScriptsAsQuery(scripts []os.DirEntry) {

	for s := 0; s < len(scripts); s++ {
		data, _ := os.ReadFile(scripts[s].Name())

		_, errs := db.Exec(string(data[:]))
		if errs != nil {
			fmt.Printf("%s \n", errs)
		}
	}

}
```

**Comment by shueybubbles** [comment]
if you are trying to run the scripts without examining the output, you could just run `sqlcmd` in the shell instead of writing your own app to do it. We have releases for most platforms.
Otherwise you would use import the `github.com/microsoft/go-sqlcmd/pkg/sqlcmd` package and use the `IncludeFile` method.

Like this test: https://github.com/microsoft/go-sqlcmd/blob/9b59da694f9cbdf87acf70589e4c680589917f1a/pkg/sqlcmd/sqlcmd_test.go#L145
